### ISSUE TITLE
Troubles with a preview of a question

### ISSUE THREAD

**Issue by mudrd8mz** [wiris/moodle-qtype_truefalsewiris#2]
I was trying to prepare a question following the steps described at http://www.wiris.com/en/quizzes/docs/moodle1/manual/true-false

My question text is like this (only the "be element of" put via the wiris editor, rest is plain text):
![image](https://cloud.githubusercontent.com/assets/85831/21929602/d66e3ce4-d991-11e6-9270-0d180731c800.png)

The algorithm works well inside the applet:
![image](https://cloud.githubusercontent.com/assets/85831/21929662/44bf85d6-d992-11e6-9d86-b1647d4aca08.png)

But then attempting to preview the questions leads to an error:
```
Sorry! The system can not generate one of the questions of the quiz.
Maybe there is a temporary connection problem right now.
Maybe the question algorithm has a bug, and fails sometimes.
Maybe it will fail always.
Don't panic...
You can retry the quiz, without penalty, just clicking Continue.
You can also tell the Teachers that there is an issue with the question titled: 'Types of numbers'

More information about this error
Debug info:
Error code: wirisquestionincorrect
Stack trace:

    line 310 of /question/type/wq/question.php: moodle_exception thrown
    line 73 of /question/type/wq/question.php: call to qtype_wq_question->call_wiris_service()
    line 45 of /question/type/truefalsewiris/question.php: call to qtype_wq_question->start_attempt()
    line 353 of /question/behaviour/behaviourbase.php: call to qtype_truefalsewiris_question->start_attempt()
    line 981 of /question/engine/questionattempt.php: call to question_behaviour->init_first_step()
    line 554 of /question/engine/questionusage.php: call to question_attempt->start()
    line 117 of /question/preview.php: call to question_usage_by_activity->start_question()
```

I can find where the exception is thrown, yet I can't find a way how to debug this. Any idea what to try and where the problem might be?

Please note that both saving and previewing a question takes a while. Is that expected?

**Comment by mudrd8mz** [comment]
Just in case it is related and can help: the `getQuizzesService()` returns an instance with the service URL set to http://hudson.wiris.info:8080/quizzes

Attempting to open that URL in my browser does not work, the address is unreachable.

**Comment by mudrd8mz** [comment]
Right. So I can confirm that editing the file `question/type/wq/quizzes/lib/integration.ini` and setting

    quizzes.service.url = "http://www.wiris.net/demo/quizzes"

fixes the issue and I can preview and use the questions properly.

It is not quite clear to me what is the relation between the files integration.ini and configuration.ini but I believe that wiris should ideally work out of box right after installation. Not all admins are able or willing to additionally modify files as described at http://www.wiris.com/en/quizzes/docs/moodle/install

**Comment by mcagigas-at-wiris** [comment]
David, 

Sorry for the inconvenience.

We just fix the problem on qtype_wq repository and upload the file to Moodle.org. integration.ini file contains defaults configuration value. We replace the http://hudson.wiris.info:8080/quizzes url for "http://www.wiris.net/demo/quizzes". The plugin works fine without any file modification.

**Comment by mudrd8mz** [comment]
OK, thanks.
