### ISSUE TITLE
dml exception thrown when editin de lang pack where truefalse wiris is installed qtype

### ISSUE THREAD

**Issue by barry-matthias** [wiris/moodle-qtype_truefalsewiris#3]
issue is being caused by module qtype_truefalsewiris, inside its /lang/de/qtype_truefalsewiris.php file there is a string id of truefalsewirisoverrideanswer_identifier_help with the following definition:

$string['truefalsewirisoverrideanswer_identifier_help'] = 'Wird die richtige Antwort festgelegt, so wird durch den entsprechenden Wert das nachstehende Feld „Richtige AntwortxE2x80 übergangen. Schreiben Sie in die Registerkarte „Variablen“ einen Algorithmus, um diese Variable auf „wahr“ oder „falsch“ zu setzen.';

i think they mean \xe2\x80\xbf as per http://www.utf8-zeichentabelle.de/unicode-utf8-table.pl?start=8192&number=128&utf8=string-literal as they seems to be using literals?

**Comment by mcagigas-at-wiris** [comment]
Hi Barry, 

Thanks for your feedback. 

We'll fix the issue in our march release. 

Best,

**Comment by mcagigas-at-wiris** [comment]
Barry, 

The issues has been fixed in our last release (3.50.1)

Best,
